import { Dumbbell, Activity, Timer, Zap, Footprints } from "lucide-react";

export const EXERCISE_DATA: Record<number, any> = {
  1: {
    id: 1,
    name: "Bicep Curls",
    title_th: "Bicep Curls",
    reps: "15 ครั้ง",
    duration: "10 นาที",
    color: "bg-blue-500",
    icon: Activity,
    iconColor: "text-blue-400",
    iconBg: "bg-blue-400/10",
    description: "การงอแขนเพื่อฝึกกล้ามเนื้อ Biceps โดยใช้ดัมเบลหรือบาร์เบล",
    how_to_score:
      "งอแขนให้สุดจนดัมเบลใกล้หัวไหล่ และเหยียดแขนให้สุดโดยไม่ล็อคข้อศอก",
    warnings: "การแกว่งตัวใช้แรงเหวี่ยง หรือเหยียดแขนไม่สุด จะถูกหักคะแนน",
  },
  2: {
    id: 2,
    name: "Squats",
    title_th: "Squats",
    reps: "25 ครั้ง",
    duration: "12 นาที",
    color: "bg-purple-500",
    icon: Zap,
    iconColor: "text-purple-400",
    iconBg: "bg-purple-400/10",
    description: "การย่อตัวลงเพื่อฝึกกล้ามเนื้อต้นขาและสะโพก",
    how_to_score: "ย่อตัวลงจนต้นขาขนานกับพื้น และยืดตัวตรงกลับสู่ท่าเริ่มต้น",
    warnings:
      "เข่ายื่นเลยปลายเท้ามากเกินไป หรือหลังงอ จะทำให้มีการแจ้งเตือนและหักคะแนน",
  },
  3: {
    id: 3,
    name: "Push-ups",
    title_th: "Push-ups",
    reps: "30 ครั้ง",
    duration: "15 นาที",
    color: "bg-orange-500",
    icon: Dumbbell,
    iconColor: "text-orange-400",
    iconBg: "bg-orange-400/10",
    description: "การดันพื้นเพื่อสร้างกล้ามเนื้อหน้าอก หัวไหล่ และหลังแขน",
    how_to_score: "ลดตัวลงจนหน้าอกเกือบแตะพื้นและดันตัวกลับขึ้นมาจนแขนตึง",
    warnings: "หลังแอ่นหรือก้นโด่งเกินไป รวมถึงการลดตัวลงไม่ลึกพอจะถูกหักคะแนน",
  },
  4: {
    id: 4,
    name: "Pull-ups",
    title_th: "Pull-ups",
    reps: "10 ครั้ง",
    duration: "12 นาที",
    color: "bg-green-500",
    icon: Activity,
    iconColor: "text-green-400",
    iconBg: "bg-green-400/10",
    description: "การดึงตัวขึ้นจากบาร์เพื่อฝึกกล้ามเนื้อหลังและแขน",
    how_to_score:
      "ดึงตัวขึ้นจนคางอยู่เหนือคานบาร์ และหย่อนตัวลงจนแขนเหยียดเกือบสุด",
    warnings: "การดิ้นหรือแกว่งขาเพื่อช่วยส่งแรง จะถูกหักคะแนนความถูกต้อง",
  },
  5: {
    id: 5,
    name: "Plank",
    title_th: "Plank",
    reps: "2 นาที",
    duration: "10 นาที",
    color: "bg-amber-500",
    icon: Timer,
    iconColor: "text-amber-400",
    iconBg: "bg-amber-400/10",
    description:
      "การเกร็งหน้าท้องในท่าเตรียมดันพื้นเพื่อสร้างความแข็งแรงของแกนกลางลำตัว",
    how_to_score: "รักษาแนวลำตัวให้ตรงเป็นเส้นขนานกับพื้นตลอดเวลาที่กำหนด",
    warnings: "การยกก้นสูงเกินไปหรือปล่อยให้หลังแอ่นจะทำให้เกิดการแจ้งเตือน",
  },
};
